// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProfileParams creates a new ProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProfileParams() *ProfileParams {
	return &ProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProfileParamsWithTimeout creates a new ProfileParams object
// with the ability to set a timeout on a request.
func NewProfileParamsWithTimeout(timeout time.Duration) *ProfileParams {
	return &ProfileParams{
		timeout: timeout,
	}
}

// NewProfileParamsWithContext creates a new ProfileParams object
// with the ability to set a context for a request.
func NewProfileParamsWithContext(ctx context.Context) *ProfileParams {
	return &ProfileParams{
		Context: ctx,
	}
}

// NewProfileParamsWithHTTPClient creates a new ProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewProfileParamsWithHTTPClient(client *http.Client) *ProfileParams {
	return &ProfileParams{
		HTTPClient: client,
	}
}

/* ProfileParams contains all the parameters to send to the API endpoint
   for the profile operation.

   Typically these are written to a http.Request.
*/
type ProfileParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProfileParams) WithDefaults() *ProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the profile params
func (o *ProfileParams) WithTimeout(timeout time.Duration) *ProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the profile params
func (o *ProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the profile params
func (o *ProfileParams) WithContext(ctx context.Context) *ProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the profile params
func (o *ProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the profile params
func (o *ProfileParams) WithHTTPClient(client *http.Client) *ProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the profile params
func (o *ProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
