// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/xy3/synche/src/models"
)

// ProfileReader is a Reader for the Profile structure.
type ProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewProfileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProfileOK creates a ProfileOK with default headers values
func NewProfileOK() *ProfileOK {
	return &ProfileOK{}
}

/* ProfileOK describes a response with status code 200, with default header values.

OK
*/
type ProfileOK struct {
	Payload *models.User
}

func (o *ProfileOK) Error() string {
	return fmt.Sprintf("[GET /user][%d] profileOK  %+v", 200, o.Payload)
}
func (o *ProfileOK) GetPayload() *models.User {
	return o.Payload
}

func (o *ProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProfileDefault creates a ProfileDefault with default headers values
func NewProfileDefault(code int) *ProfileDefault {
	return &ProfileDefault{
		_statusCode: code,
	}
}

/* ProfileDefault describes a response with status code -1, with default header values.

Error
*/
type ProfileDefault struct {
	_statusCode int

	Payload models.Error
}

// Code gets the status code for the profile default response
func (o *ProfileDefault) Code() int {
	return o._statusCode
}

func (o *ProfileDefault) Error() string {
	return fmt.Sprintf("[GET /user][%d] profile default  %+v", o._statusCode, o.Payload)
}
func (o *ProfileDefault) GetPayload() models.Error {
	return o.Payload
}

func (o *ProfileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
