// Code generated by go-swagger; DO NOT EDIT.

package testing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCheckGetParams creates a new CheckGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCheckGetParams() *CheckGetParams {
	return &CheckGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCheckGetParamsWithTimeout creates a new CheckGetParams object
// with the ability to set a timeout on a request.
func NewCheckGetParamsWithTimeout(timeout time.Duration) *CheckGetParams {
	return &CheckGetParams{
		timeout: timeout,
	}
}

// NewCheckGetParamsWithContext creates a new CheckGetParams object
// with the ability to set a context for a request.
func NewCheckGetParamsWithContext(ctx context.Context) *CheckGetParams {
	return &CheckGetParams{
		Context: ctx,
	}
}

// NewCheckGetParamsWithHTTPClient creates a new CheckGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewCheckGetParamsWithHTTPClient(client *http.Client) *CheckGetParams {
	return &CheckGetParams{
		HTTPClient: client,
	}
}

/* CheckGetParams contains all the parameters to send to the API endpoint
   for the check get operation.

   Typically these are written to a http.Request.
*/
type CheckGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the check get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckGetParams) WithDefaults() *CheckGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the check get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the check get params
func (o *CheckGetParams) WithTimeout(timeout time.Duration) *CheckGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check get params
func (o *CheckGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check get params
func (o *CheckGetParams) WithContext(ctx context.Context) *CheckGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check get params
func (o *CheckGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check get params
func (o *CheckGetParams) WithHTTPClient(client *http.Client) *CheckGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check get params
func (o *CheckGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CheckGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
