// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCheckUploadedChunksParams creates a new CheckUploadedChunksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCheckUploadedChunksParams() *CheckUploadedChunksParams {
	return &CheckUploadedChunksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCheckUploadedChunksParamsWithTimeout creates a new CheckUploadedChunksParams object
// with the ability to set a timeout on a request.
func NewCheckUploadedChunksParamsWithTimeout(timeout time.Duration) *CheckUploadedChunksParams {
	return &CheckUploadedChunksParams{
		timeout: timeout,
	}
}

// NewCheckUploadedChunksParamsWithContext creates a new CheckUploadedChunksParams object
// with the ability to set a context for a request.
func NewCheckUploadedChunksParamsWithContext(ctx context.Context) *CheckUploadedChunksParams {
	return &CheckUploadedChunksParams{
		Context: ctx,
	}
}

// NewCheckUploadedChunksParamsWithHTTPClient creates a new CheckUploadedChunksParams object
// with the ability to set a custom HTTPClient for a request.
func NewCheckUploadedChunksParamsWithHTTPClient(client *http.Client) *CheckUploadedChunksParams {
	return &CheckUploadedChunksParams{
		HTTPClient: client,
	}
}

/* CheckUploadedChunksParams contains all the parameters to send to the API endpoint
   for the check uploaded chunks operation.

   Typically these are written to a http.Request.
*/
type CheckUploadedChunksParams struct {

	// FileID.
	//
	// Format: uint
	FileID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the check uploaded chunks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckUploadedChunksParams) WithDefaults() *CheckUploadedChunksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the check uploaded chunks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckUploadedChunksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the check uploaded chunks params
func (o *CheckUploadedChunksParams) WithTimeout(timeout time.Duration) *CheckUploadedChunksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check uploaded chunks params
func (o *CheckUploadedChunksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check uploaded chunks params
func (o *CheckUploadedChunksParams) WithContext(ctx context.Context) *CheckUploadedChunksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check uploaded chunks params
func (o *CheckUploadedChunksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check uploaded chunks params
func (o *CheckUploadedChunksParams) WithHTTPClient(client *http.Client) *CheckUploadedChunksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check uploaded chunks params
func (o *CheckUploadedChunksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileID adds the fileID to the check uploaded chunks params
func (o *CheckUploadedChunksParams) WithFileID(fileID uint64) *CheckUploadedChunksParams {
	o.SetFileID(fileID)
	return o
}

// SetFileID adds the fileId to the check uploaded chunks params
func (o *CheckUploadedChunksParams) SetFileID(fileID uint64) {
	o.FileID = fileID
}

// WriteToRequest writes these params to a swagger request
func (o *CheckUploadedChunksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param fileID
	qrFileID := o.FileID
	qFileID := swag.FormatUint64(qrFileID)
	if qFileID != "" {

		if err := r.SetQueryParam("fileID", qFileID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
