// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gitlab.computing.dcu.ie/collint9/2021-ca400-collint9-coynemt2/src/server/models"
)

// ListFilesOKCode is the HTTP code returned for type ListFilesOK
const ListFilesOKCode int = 200

/*ListFilesOK OK

swagger:response listFilesOK
*/
type ListFilesOK struct {

	/*
	  In: Body
	*/
	Payload *models.DirectoryContents `json:"body,omitempty"`
}

// NewListFilesOK creates ListFilesOK with default headers values
func NewListFilesOK() *ListFilesOK {

	return &ListFilesOK{}
}

// WithPayload adds the payload to the list files o k response
func (o *ListFilesOK) WithPayload(payload *models.DirectoryContents) *ListFilesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list files o k response
func (o *ListFilesOK) SetPayload(payload *models.DirectoryContents) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListFilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListFilesNotImplementedCode is the HTTP code returned for type ListFilesNotImplemented
const ListFilesNotImplementedCode int = 501

/*ListFilesNotImplemented not implemented

swagger:response listFilesNotImplemented
*/
type ListFilesNotImplemented struct {

	/*
	  In: Body
	*/
	Payload models.NotImplemented `json:"body,omitempty"`
}

// NewListFilesNotImplemented creates ListFilesNotImplemented with default headers values
func NewListFilesNotImplemented() *ListFilesNotImplemented {

	return &ListFilesNotImplemented{}
}

// WithPayload adds the payload to the list files not implemented response
func (o *ListFilesNotImplemented) WithPayload(payload models.NotImplemented) *ListFilesNotImplemented {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list files not implemented response
func (o *ListFilesNotImplemented) SetPayload(payload models.NotImplemented) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListFilesNotImplemented) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(501)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
