// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Synche
//
//  Synche Server API
//  Schemes:
//    http
//  Host: 127.0.0.1:9449
//  BasePath: /v1/api
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <you@your-company.com>
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
