// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DirectoryListRequest directory list request
//
// swagger:model DirectoryListRequest
type DirectoryListRequest struct {

	// directory Id
	DirectoryID DirectoryID `json:"directoryId,omitempty"`

	// the limit of file results to return
	// Example: 10
	Limit *int64 `json:"limit,omitempty"`
}

// Validate validates this directory list request
func (m *DirectoryListRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDirectoryID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DirectoryListRequest) validateDirectoryID(formats strfmt.Registry) error {
	if swag.IsZero(m.DirectoryID) { // not required
		return nil
	}

	if err := m.DirectoryID.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("directoryId")
		}
		return err
	}

	return nil
}

// ContextValidate validate this directory list request based on the context it is used
func (m *DirectoryListRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDirectoryID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DirectoryListRequest) contextValidateDirectoryID(ctx context.Context, formats strfmt.Registry) error {

	if err := m.DirectoryID.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("directoryId")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DirectoryListRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DirectoryListRequest) UnmarshalBinary(b []byte) error {
	var res DirectoryListRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
