// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DirectoryContents directory contents
//
// swagger:model DirectoryContents
type DirectoryContents struct {

	// directory Id
	// Format: uuid
	DirectoryID DirectoryID `json:"directoryId,omitempty"`

	// the contents of the directory
	// Example: ["file1","file2","directory1/"]
	Listings []string `json:"listings"`
}

// Validate validates this directory contents
func (m *DirectoryContents) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDirectoryID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DirectoryContents) validateDirectoryID(formats strfmt.Registry) error {
	if swag.IsZero(m.DirectoryID) { // not required
		return nil
	}

	if err := m.DirectoryID.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("directoryId")
		}
		return err
	}

	return nil
}

// ContextValidate validate this directory contents based on the context it is used
func (m *DirectoryContents) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDirectoryID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DirectoryContents) contextValidateDirectoryID(ctx context.Context, formats strfmt.Registry) error {

	if err := m.DirectoryID.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("directoryId")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DirectoryContents) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DirectoryContents) UnmarshalBinary(b []byte) error {
	var res DirectoryContents
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
