// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// NotImplemented not implemented
//
// swagger:model NotImplemented
type NotImplemented string

// Validate validates this not implemented
func (m NotImplemented) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this not implemented based on context it is used
func (m NotImplemented) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
