// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UploadedChunk uploaded chunk
//
// swagger:model UploadedChunk
type UploadedChunk struct {

	// directory ID
	DirectoryID int64 `json:"DirectoryID,omitempty"`

	// The id of the file this chunk is a part of
	FileID int64 `json:"FileID,omitempty"`

	// The file hash of the chunk
	Hash string `json:"Hash,omitempty"`
}

// Validate validates this uploaded chunk
func (m *UploadedChunk) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this uploaded chunk based on context it is used
func (m *UploadedChunk) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UploadedChunk) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UploadedChunk) UnmarshalBinary(b []byte) error {
	var res UploadedChunk
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
