// Code generated by go-swagger; DO NOT EDIT.

package testing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gitlab.computing.dcu.ie/collint9/2021-ca400-collint9-coynemt2/src/server/models"
)

// CheckGetOKCode is the HTTP code returned for type CheckGetOK
const CheckGetOKCode int = 200

/*CheckGetOK OK

swagger:response checkGetOK
*/
type CheckGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewCheckGetOK creates CheckGetOK with default headers values
func NewCheckGetOK() *CheckGetOK {

	return &CheckGetOK{}
}

// WithPayload adds the payload to the check get o k response
func (o *CheckGetOK) WithPayload(payload *models.Message) *CheckGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check get o k response
func (o *CheckGetOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
