// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new files API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for files API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	ListFiles(params *ListFilesParams) (*ListFilesOK, error)

	NewUpload(params *NewUploadParams) (*NewUploadOK, error)

	UploadChunk(params *UploadChunkParams) (*UploadChunkCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ListFiles lists the files on the server

  Queries the server for the files and their locations stored on the server
*/
func (a *Client) ListFiles(params *ListFilesParams) (*ListFilesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListFilesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listFiles",
		Method:             "GET",
		PathPattern:        "/list",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListFilesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListFilesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listFiles: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  NewUpload requests to initiate a new file upload

  To upload a file to the server, a new upload request must be sent to this endpoint with the required information about the file
*/
func (a *Client) NewUpload(params *NewUploadParams) (*NewUploadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewNewUploadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "newUpload",
		Method:             "POST",
		PathPattern:        "/upload/new",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &NewUploadReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*NewUploadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for newUpload: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  UploadChunk adds an inventory item

  Uploads a new chunk to the Synche server
*/
func (a *Client) UploadChunk(params *UploadChunkParams) (*UploadChunkCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUploadChunkParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "uploadChunk",
		Method:             "POST",
		PathPattern:        "/upload/chunk",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UploadChunkReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UploadChunkCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for uploadChunk: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
