// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/xy3/synche/src/client/models"
)

// CreateDirPathReader is a Reader for the CreateDirPath structure.
type CreateDirPathReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDirPathReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateDirPathOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateDirPathUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCreateDirPathDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateDirPathOK creates a CreateDirPathOK with default headers values
func NewCreateDirPathOK() *CreateDirPathOK {
	return &CreateDirPathOK{}
}

/* CreateDirPathOK describes a response with status code 200, with default header values.

OK
*/
type CreateDirPathOK struct {
	Payload *models.Directory
}

func (o *CreateDirPathOK) Error() string {
	return fmt.Sprintf("[PUT /directoryPath/{dirPath}][%d] createDirPathOK  %+v", 200, o.Payload)
}
func (o *CreateDirPathOK) GetPayload() *models.Directory {
	return o.Payload
}

func (o *CreateDirPathOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Directory)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDirPathUnauthorized creates a CreateDirPathUnauthorized with default headers values
func NewCreateDirPathUnauthorized() *CreateDirPathUnauthorized {
	return &CreateDirPathUnauthorized{}
}

/* CreateDirPathUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateDirPathUnauthorized struct {
}

func (o *CreateDirPathUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /directoryPath/{dirPath}][%d] createDirPathUnauthorized ", 401)
}

func (o *CreateDirPathUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDirPathDefault creates a CreateDirPathDefault with default headers values
func NewCreateDirPathDefault(code int) *CreateDirPathDefault {
	return &CreateDirPathDefault{
		_statusCode: code,
	}
}

/* CreateDirPathDefault describes a response with status code -1, with default header values.

Error
*/
type CreateDirPathDefault struct {
	_statusCode int

	Payload models.Error
}

// Code gets the status code for the create dir path default response
func (o *CreateDirPathDefault) Code() int {
	return o._statusCode
}

func (o *CreateDirPathDefault) Error() string {
	return fmt.Sprintf("[PUT /directoryPath/{dirPath}][%d] createDirPath default  %+v", o._statusCode, o.Payload)
}
func (o *CreateDirPathDefault) GetPayload() models.Error {
	return o.Payload
}

func (o *CreateDirPathDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
