// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateDirPathParams creates a new CreateDirPathParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateDirPathParams() *CreateDirPathParams {
	return &CreateDirPathParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDirPathParamsWithTimeout creates a new CreateDirPathParams object
// with the ability to set a timeout on a request.
func NewCreateDirPathParamsWithTimeout(timeout time.Duration) *CreateDirPathParams {
	return &CreateDirPathParams{
		timeout: timeout,
	}
}

// NewCreateDirPathParamsWithContext creates a new CreateDirPathParams object
// with the ability to set a context for a request.
func NewCreateDirPathParamsWithContext(ctx context.Context) *CreateDirPathParams {
	return &CreateDirPathParams{
		Context: ctx,
	}
}

// NewCreateDirPathParamsWithHTTPClient creates a new CreateDirPathParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateDirPathParamsWithHTTPClient(client *http.Client) *CreateDirPathParams {
	return &CreateDirPathParams{
		HTTPClient: client,
	}
}

/* CreateDirPathParams contains all the parameters to send to the API endpoint
   for the create dir path operation.

   Typically these are written to a http.Request.
*/
type CreateDirPathParams struct {

	// DirPath.
	DirPath string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create dir path params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDirPathParams) WithDefaults() *CreateDirPathParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create dir path params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDirPathParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create dir path params
func (o *CreateDirPathParams) WithTimeout(timeout time.Duration) *CreateDirPathParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create dir path params
func (o *CreateDirPathParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create dir path params
func (o *CreateDirPathParams) WithContext(ctx context.Context) *CreateDirPathParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create dir path params
func (o *CreateDirPathParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create dir path params
func (o *CreateDirPathParams) WithHTTPClient(client *http.Client) *CreateDirPathParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create dir path params
func (o *CreateDirPathParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDirPath adds the dirPath to the create dir path params
func (o *CreateDirPathParams) WithDirPath(dirPath string) *CreateDirPathParams {
	o.SetDirPath(dirPath)
	return o
}

// SetDirPath adds the dirPath to the create dir path params
func (o *CreateDirPathParams) SetDirPath(dirPath string) {
	o.DirPath = dirPath
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDirPathParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dirPath
	if err := r.SetPathParam("dirPath", o.DirPath); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
