// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteFilepathParams creates a new DeleteFilepathParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteFilepathParams() *DeleteFilepathParams {
	return &DeleteFilepathParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFilepathParamsWithTimeout creates a new DeleteFilepathParams object
// with the ability to set a timeout on a request.
func NewDeleteFilepathParamsWithTimeout(timeout time.Duration) *DeleteFilepathParams {
	return &DeleteFilepathParams{
		timeout: timeout,
	}
}

// NewDeleteFilepathParamsWithContext creates a new DeleteFilepathParams object
// with the ability to set a context for a request.
func NewDeleteFilepathParamsWithContext(ctx context.Context) *DeleteFilepathParams {
	return &DeleteFilepathParams{
		Context: ctx,
	}
}

// NewDeleteFilepathParamsWithHTTPClient creates a new DeleteFilepathParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteFilepathParamsWithHTTPClient(client *http.Client) *DeleteFilepathParams {
	return &DeleteFilepathParams{
		HTTPClient: client,
	}
}

/* DeleteFilepathParams contains all the parameters to send to the API endpoint
   for the delete filepath operation.

   Typically these are written to a http.Request.
*/
type DeleteFilepathParams struct {

	// FilePath.
	FilePath string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete filepath params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteFilepathParams) WithDefaults() *DeleteFilepathParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete filepath params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteFilepathParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete filepath params
func (o *DeleteFilepathParams) WithTimeout(timeout time.Duration) *DeleteFilepathParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete filepath params
func (o *DeleteFilepathParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete filepath params
func (o *DeleteFilepathParams) WithContext(ctx context.Context) *DeleteFilepathParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete filepath params
func (o *DeleteFilepathParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete filepath params
func (o *DeleteFilepathParams) WithHTTPClient(client *http.Client) *DeleteFilepathParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete filepath params
func (o *DeleteFilepathParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilePath adds the filePath to the delete filepath params
func (o *DeleteFilepathParams) WithFilePath(filePath string) *DeleteFilepathParams {
	o.SetFilePath(filePath)
	return o
}

// SetFilePath adds the filePath to the delete filepath params
func (o *DeleteFilepathParams) SetFilePath(filePath string) {
	o.FilePath = filePath
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFilepathParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param filePath
	if err := r.SetPathParam("filePath", o.FilePath); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
