// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteDirPathParams creates a new DeleteDirPathParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteDirPathParams() *DeleteDirPathParams {
	return &DeleteDirPathParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDirPathParamsWithTimeout creates a new DeleteDirPathParams object
// with the ability to set a timeout on a request.
func NewDeleteDirPathParamsWithTimeout(timeout time.Duration) *DeleteDirPathParams {
	return &DeleteDirPathParams{
		timeout: timeout,
	}
}

// NewDeleteDirPathParamsWithContext creates a new DeleteDirPathParams object
// with the ability to set a context for a request.
func NewDeleteDirPathParamsWithContext(ctx context.Context) *DeleteDirPathParams {
	return &DeleteDirPathParams{
		Context: ctx,
	}
}

// NewDeleteDirPathParamsWithHTTPClient creates a new DeleteDirPathParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteDirPathParamsWithHTTPClient(client *http.Client) *DeleteDirPathParams {
	return &DeleteDirPathParams{
		HTTPClient: client,
	}
}

/* DeleteDirPathParams contains all the parameters to send to the API endpoint
   for the delete dir path operation.

   Typically these are written to a http.Request.
*/
type DeleteDirPathParams struct {

	// DirPath.
	DirPath string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete dir path params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDirPathParams) WithDefaults() *DeleteDirPathParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete dir path params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDirPathParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete dir path params
func (o *DeleteDirPathParams) WithTimeout(timeout time.Duration) *DeleteDirPathParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete dir path params
func (o *DeleteDirPathParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete dir path params
func (o *DeleteDirPathParams) WithContext(ctx context.Context) *DeleteDirPathParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete dir path params
func (o *DeleteDirPathParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete dir path params
func (o *DeleteDirPathParams) WithHTTPClient(client *http.Client) *DeleteDirPathParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete dir path params
func (o *DeleteDirPathParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDirPath adds the dirPath to the delete dir path params
func (o *DeleteDirPathParams) WithDirPath(dirPath string) *DeleteDirPathParams {
	o.SetDirPath(dirPath)
	return o
}

// SetDirPath adds the dirPath to the delete dir path params
func (o *DeleteDirPathParams) SetDirPath(dirPath string) {
	o.DirPath = dirPath
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDirPathParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dirPath
	if err := r.SetPathParam("dirPath", o.DirPath); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
