// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteDirectoryParams creates a new DeleteDirectoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteDirectoryParams() *DeleteDirectoryParams {
	return &DeleteDirectoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDirectoryParamsWithTimeout creates a new DeleteDirectoryParams object
// with the ability to set a timeout on a request.
func NewDeleteDirectoryParamsWithTimeout(timeout time.Duration) *DeleteDirectoryParams {
	return &DeleteDirectoryParams{
		timeout: timeout,
	}
}

// NewDeleteDirectoryParamsWithContext creates a new DeleteDirectoryParams object
// with the ability to set a context for a request.
func NewDeleteDirectoryParamsWithContext(ctx context.Context) *DeleteDirectoryParams {
	return &DeleteDirectoryParams{
		Context: ctx,
	}
}

// NewDeleteDirectoryParamsWithHTTPClient creates a new DeleteDirectoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteDirectoryParamsWithHTTPClient(client *http.Client) *DeleteDirectoryParams {
	return &DeleteDirectoryParams{
		HTTPClient: client,
	}
}

/* DeleteDirectoryParams contains all the parameters to send to the API endpoint
   for the delete directory operation.

   Typically these are written to a http.Request.
*/
type DeleteDirectoryParams struct {

	// ID.
	//
	// Format: uint
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete directory params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDirectoryParams) WithDefaults() *DeleteDirectoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete directory params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDirectoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete directory params
func (o *DeleteDirectoryParams) WithTimeout(timeout time.Duration) *DeleteDirectoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete directory params
func (o *DeleteDirectoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete directory params
func (o *DeleteDirectoryParams) WithContext(ctx context.Context) *DeleteDirectoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete directory params
func (o *DeleteDirectoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete directory params
func (o *DeleteDirectoryParams) WithHTTPClient(client *http.Client) *DeleteDirectoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete directory params
func (o *DeleteDirectoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete directory params
func (o *DeleteDirectoryParams) WithID(id uint64) *DeleteDirectoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete directory params
func (o *DeleteDirectoryParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDirectoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
