// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/xy3/synche/src/models"
)

// DeleteDirPathReader is a Reader for the DeleteDirPath structure.
type DeleteDirPathReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDirPathReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteDirPathOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteDirPathUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewDeleteDirPathNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteDirPathDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteDirPathOK creates a DeleteDirPathOK with default headers values
func NewDeleteDirPathOK() *DeleteDirPathOK {
	return &DeleteDirPathOK{}
}

/* DeleteDirPathOK describes a response with status code 200, with default header values.

OK
*/
type DeleteDirPathOK struct {
}

func (o *DeleteDirPathOK) Error() string {
	return fmt.Sprintf("[DELETE /directoryPath/{dirPath}][%d] deleteDirPathOK ", 200)
}

func (o *DeleteDirPathOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDirPathUnauthorized creates a DeleteDirPathUnauthorized with default headers values
func NewDeleteDirPathUnauthorized() *DeleteDirPathUnauthorized {
	return &DeleteDirPathUnauthorized{}
}

/* DeleteDirPathUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteDirPathUnauthorized struct {
}

func (o *DeleteDirPathUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /directoryPath/{dirPath}][%d] deleteDirPathUnauthorized ", 401)
}

func (o *DeleteDirPathUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDirPathNotImplemented creates a DeleteDirPathNotImplemented with default headers values
func NewDeleteDirPathNotImplemented() *DeleteDirPathNotImplemented {
	return &DeleteDirPathNotImplemented{}
}

/* DeleteDirPathNotImplemented describes a response with status code 501, with default header values.

Not implemented
*/
type DeleteDirPathNotImplemented struct {
}

func (o *DeleteDirPathNotImplemented) Error() string {
	return fmt.Sprintf("[DELETE /directoryPath/{dirPath}][%d] deleteDirPathNotImplemented ", 501)
}

func (o *DeleteDirPathNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDirPathDefault creates a DeleteDirPathDefault with default headers values
func NewDeleteDirPathDefault(code int) *DeleteDirPathDefault {
	return &DeleteDirPathDefault{
		_statusCode: code,
	}
}

/* DeleteDirPathDefault describes a response with status code -1, with default header values.

Error
*/
type DeleteDirPathDefault struct {
	_statusCode int

	Payload models.Error
}

// Code gets the status code for the delete dir path default response
func (o *DeleteDirPathDefault) Code() int {
	return o._statusCode
}

func (o *DeleteDirPathDefault) Error() string {
	return fmt.Sprintf("[DELETE /directoryPath/{dirPath}][%d] deleteDirPath default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteDirPathDefault) GetPayload() models.Error {
	return o.Payload
}

func (o *DeleteDirPathDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
