// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListDirPathInfoParams creates a new ListDirPathInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListDirPathInfoParams() *ListDirPathInfoParams {
	return &ListDirPathInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListDirPathInfoParamsWithTimeout creates a new ListDirPathInfoParams object
// with the ability to set a timeout on a request.
func NewListDirPathInfoParamsWithTimeout(timeout time.Duration) *ListDirPathInfoParams {
	return &ListDirPathInfoParams{
		timeout: timeout,
	}
}

// NewListDirPathInfoParamsWithContext creates a new ListDirPathInfoParams object
// with the ability to set a context for a request.
func NewListDirPathInfoParamsWithContext(ctx context.Context) *ListDirPathInfoParams {
	return &ListDirPathInfoParams{
		Context: ctx,
	}
}

// NewListDirPathInfoParamsWithHTTPClient creates a new ListDirPathInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewListDirPathInfoParamsWithHTTPClient(client *http.Client) *ListDirPathInfoParams {
	return &ListDirPathInfoParams{
		HTTPClient: client,
	}
}

/* ListDirPathInfoParams contains all the parameters to send to the API endpoint
   for the list dir path info operation.

   Typically these are written to a http.Request.
*/
type ListDirPathInfoParams struct {

	// DirPath.
	DirPath string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list dir path info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListDirPathInfoParams) WithDefaults() *ListDirPathInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list dir path info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListDirPathInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list dir path info params
func (o *ListDirPathInfoParams) WithTimeout(timeout time.Duration) *ListDirPathInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list dir path info params
func (o *ListDirPathInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list dir path info params
func (o *ListDirPathInfoParams) WithContext(ctx context.Context) *ListDirPathInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list dir path info params
func (o *ListDirPathInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list dir path info params
func (o *ListDirPathInfoParams) WithHTTPClient(client *http.Client) *ListDirPathInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list dir path info params
func (o *ListDirPathInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDirPath adds the dirPath to the list dir path info params
func (o *ListDirPathInfoParams) WithDirPath(dirPath string) *ListDirPathInfoParams {
	o.SetDirPath(dirPath)
	return o
}

// SetDirPath adds the dirPath to the list dir path info params
func (o *ListDirPathInfoParams) SetDirPath(dirPath string) {
	o.DirPath = dirPath
}

// WriteToRequest writes these params to a swagger request
func (o *ListDirPathInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dirPath
	if err := r.SetPathParam("dirPath", o.DirPath); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
