// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListHomeDirectoryParams creates a new ListHomeDirectoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListHomeDirectoryParams() *ListHomeDirectoryParams {
	return &ListHomeDirectoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListHomeDirectoryParamsWithTimeout creates a new ListHomeDirectoryParams object
// with the ability to set a timeout on a request.
func NewListHomeDirectoryParamsWithTimeout(timeout time.Duration) *ListHomeDirectoryParams {
	return &ListHomeDirectoryParams{
		timeout: timeout,
	}
}

// NewListHomeDirectoryParamsWithContext creates a new ListHomeDirectoryParams object
// with the ability to set a context for a request.
func NewListHomeDirectoryParamsWithContext(ctx context.Context) *ListHomeDirectoryParams {
	return &ListHomeDirectoryParams{
		Context: ctx,
	}
}

// NewListHomeDirectoryParamsWithHTTPClient creates a new ListHomeDirectoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewListHomeDirectoryParamsWithHTTPClient(client *http.Client) *ListHomeDirectoryParams {
	return &ListHomeDirectoryParams{
		HTTPClient: client,
	}
}

/* ListHomeDirectoryParams contains all the parameters to send to the API endpoint
   for the list home directory operation.

   Typically these are written to a http.Request.
*/
type ListHomeDirectoryParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list home directory params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListHomeDirectoryParams) WithDefaults() *ListHomeDirectoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list home directory params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListHomeDirectoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list home directory params
func (o *ListHomeDirectoryParams) WithTimeout(timeout time.Duration) *ListHomeDirectoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list home directory params
func (o *ListHomeDirectoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list home directory params
func (o *ListHomeDirectoryParams) WithContext(ctx context.Context) *ListHomeDirectoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list home directory params
func (o *ListHomeDirectoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list home directory params
func (o *ListHomeDirectoryParams) WithHTTPClient(client *http.Client) *ListHomeDirectoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list home directory params
func (o *ListHomeDirectoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListHomeDirectoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
