// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListDirectoryParams creates a new ListDirectoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListDirectoryParams() *ListDirectoryParams {
	return &ListDirectoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListDirectoryParamsWithTimeout creates a new ListDirectoryParams object
// with the ability to set a timeout on a request.
func NewListDirectoryParamsWithTimeout(timeout time.Duration) *ListDirectoryParams {
	return &ListDirectoryParams{
		timeout: timeout,
	}
}

// NewListDirectoryParamsWithContext creates a new ListDirectoryParams object
// with the ability to set a context for a request.
func NewListDirectoryParamsWithContext(ctx context.Context) *ListDirectoryParams {
	return &ListDirectoryParams{
		Context: ctx,
	}
}

// NewListDirectoryParamsWithHTTPClient creates a new ListDirectoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewListDirectoryParamsWithHTTPClient(client *http.Client) *ListDirectoryParams {
	return &ListDirectoryParams{
		HTTPClient: client,
	}
}

/* ListDirectoryParams contains all the parameters to send to the API endpoint
   for the list directory operation.

   Typically these are written to a http.Request.
*/
type ListDirectoryParams struct {

	// ID.
	//
	// Format: uint
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list directory params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListDirectoryParams) WithDefaults() *ListDirectoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list directory params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListDirectoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list directory params
func (o *ListDirectoryParams) WithTimeout(timeout time.Duration) *ListDirectoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list directory params
func (o *ListDirectoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list directory params
func (o *ListDirectoryParams) WithContext(ctx context.Context) *ListDirectoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list directory params
func (o *ListDirectoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list directory params
func (o *ListDirectoryParams) WithHTTPClient(client *http.Client) *ListDirectoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list directory params
func (o *ListDirectoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list directory params
func (o *ListDirectoryParams) WithID(id uint64) *ListDirectoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list directory params
func (o *ListDirectoryParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListDirectoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
