// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/xy3/synche/src/models"
)

// ListHomeDirectoryReader is a Reader for the ListHomeDirectory structure.
type ListHomeDirectoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListHomeDirectoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListHomeDirectoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListHomeDirectoryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewListHomeDirectoryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListHomeDirectoryOK creates a ListHomeDirectoryOK with default headers values
func NewListHomeDirectoryOK() *ListHomeDirectoryOK {
	return &ListHomeDirectoryOK{}
}

/* ListHomeDirectoryOK describes a response with status code 200, with default header values.

OK
*/
type ListHomeDirectoryOK struct {
	Payload *models.DirectoryContents
}

func (o *ListHomeDirectoryOK) Error() string {
	return fmt.Sprintf("[GET /directory][%d] listHomeDirectoryOK  %+v", 200, o.Payload)
}
func (o *ListHomeDirectoryOK) GetPayload() *models.DirectoryContents {
	return o.Payload
}

func (o *ListHomeDirectoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DirectoryContents)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListHomeDirectoryUnauthorized creates a ListHomeDirectoryUnauthorized with default headers values
func NewListHomeDirectoryUnauthorized() *ListHomeDirectoryUnauthorized {
	return &ListHomeDirectoryUnauthorized{}
}

/* ListHomeDirectoryUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ListHomeDirectoryUnauthorized struct {
}

func (o *ListHomeDirectoryUnauthorized) Error() string {
	return fmt.Sprintf("[GET /directory][%d] listHomeDirectoryUnauthorized ", 401)
}

func (o *ListHomeDirectoryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListHomeDirectoryDefault creates a ListHomeDirectoryDefault with default headers values
func NewListHomeDirectoryDefault(code int) *ListHomeDirectoryDefault {
	return &ListHomeDirectoryDefault{
		_statusCode: code,
	}
}

/* ListHomeDirectoryDefault describes a response with status code -1, with default header values.

Error
*/
type ListHomeDirectoryDefault struct {
	_statusCode int

	Payload models.Error
}

// Code gets the status code for the list home directory default response
func (o *ListHomeDirectoryDefault) Code() int {
	return o._statusCode
}

func (o *ListHomeDirectoryDefault) Error() string {
	return fmt.Sprintf("[GET /directory][%d] listHomeDirectory default  %+v", o._statusCode, o.Payload)
}
func (o *ListHomeDirectoryDefault) GetPayload() models.Error {
	return o.Payload
}

func (o *ListHomeDirectoryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
