// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/xy3/synche/src/models"
)

// NewUpdateFileByPathParams creates a new UpdateFileByPathParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateFileByPathParams() *UpdateFileByPathParams {
	return &UpdateFileByPathParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateFileByPathParamsWithTimeout creates a new UpdateFileByPathParams object
// with the ability to set a timeout on a request.
func NewUpdateFileByPathParamsWithTimeout(timeout time.Duration) *UpdateFileByPathParams {
	return &UpdateFileByPathParams{
		timeout: timeout,
	}
}

// NewUpdateFileByPathParamsWithContext creates a new UpdateFileByPathParams object
// with the ability to set a context for a request.
func NewUpdateFileByPathParamsWithContext(ctx context.Context) *UpdateFileByPathParams {
	return &UpdateFileByPathParams{
		Context: ctx,
	}
}

// NewUpdateFileByPathParamsWithHTTPClient creates a new UpdateFileByPathParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateFileByPathParamsWithHTTPClient(client *http.Client) *UpdateFileByPathParams {
	return &UpdateFileByPathParams{
		HTTPClient: client,
	}
}

/* UpdateFileByPathParams contains all the parameters to send to the API endpoint
   for the update file by path operation.

   Typically these are written to a http.Request.
*/
type UpdateFileByPathParams struct {

	// FilePath.
	FilePath string

	// FileUpdate.
	FileUpdate *models.FileUpdate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update file by path params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateFileByPathParams) WithDefaults() *UpdateFileByPathParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update file by path params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateFileByPathParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update file by path params
func (o *UpdateFileByPathParams) WithTimeout(timeout time.Duration) *UpdateFileByPathParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update file by path params
func (o *UpdateFileByPathParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update file by path params
func (o *UpdateFileByPathParams) WithContext(ctx context.Context) *UpdateFileByPathParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update file by path params
func (o *UpdateFileByPathParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update file by path params
func (o *UpdateFileByPathParams) WithHTTPClient(client *http.Client) *UpdateFileByPathParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update file by path params
func (o *UpdateFileByPathParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilePath adds the filePath to the update file by path params
func (o *UpdateFileByPathParams) WithFilePath(filePath string) *UpdateFileByPathParams {
	o.SetFilePath(filePath)
	return o
}

// SetFilePath adds the filePath to the update file by path params
func (o *UpdateFileByPathParams) SetFilePath(filePath string) {
	o.FilePath = filePath
}

// WithFileUpdate adds the fileUpdate to the update file by path params
func (o *UpdateFileByPathParams) WithFileUpdate(fileUpdate *models.FileUpdate) *UpdateFileByPathParams {
	o.SetFileUpdate(fileUpdate)
	return o
}

// SetFileUpdate adds the fileUpdate to the update file by path params
func (o *UpdateFileByPathParams) SetFileUpdate(fileUpdate *models.FileUpdate) {
	o.FileUpdate = fileUpdate
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateFileByPathParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param filePath
	if err := r.SetPathParam("filePath", o.FilePath); err != nil {
		return err
	}
	if o.FileUpdate != nil {
		if err := r.SetBodyParam(o.FileUpdate); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
