// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Directory Directory information
//
// swagger:model Directory
type Directory struct {

	// file count
	FileCount uint64 `json:"FileCount,omitempty"`

	// ID
	ID uint64 `json:"ID,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// parent directory ID
	ParentDirectoryID uint64 `json:"ParentDirectoryID,omitempty"`

	// path
	Path string `json:"Path,omitempty"`

	// path hash
	PathHash string `json:"PathHash,omitempty"`
}

// Validate validates this directory
func (m *Directory) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this directory based on context it is used
func (m *Directory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Directory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Directory) UnmarshalBinary(b []byte) error {
	var res Directory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
