// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExistingChunks existing chunks
//
// swagger:model ExistingChunks
type ExistingChunks struct {

	// chunk numbers
	// Required: true
	ChunkNumbers []int64 `json:"chunkNumbers"`
}

// Validate validates this existing chunks
func (m *ExistingChunks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChunkNumbers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExistingChunks) validateChunkNumbers(formats strfmt.Registry) error {

	if err := validate.Required("chunkNumbers", "body", m.ChunkNumbers); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this existing chunks based on context it is used
func (m *ExistingChunks) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExistingChunks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExistingChunks) UnmarshalBinary(b []byte) error {
	var res ExistingChunks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
