// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FileUpdate The file attributes to update
//
// Min Properties: 1
//
// swagger:model FileUpdate
type FileUpdate struct {

	// new directory ID
	NewDirectoryID uint64 `json:"NewDirectoryID,omitempty"`

	// new file name
	NewFileName string `json:"NewFileName,omitempty"`

	// new file path
	NewFilePath string `json:"NewFilePath,omitempty"`
}

// Validate validates this file update
func (m *FileUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this file update based on context it is used
func (m *FileUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FileUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FileUpdate) UnmarshalBinary(b []byte) error {
	var res FileUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
