// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FileChunk A chunk with a reference to the file it is a part of
//
// swagger:model FileChunk
type FileChunk struct {

	// chunk
	Chunk *Chunk `json:"Chunk,omitempty"`

	// file ID
	FileID uint64 `json:"FileID,omitempty"`

	// ID
	ID uint64 `json:"ID,omitempty"`

	// the position of the chunk in the file
	Number int64 `json:"Number,omitempty"`
}

// Validate validates this file chunk
func (m *FileChunk) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChunk(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FileChunk) validateChunk(formats strfmt.Registry) error {
	if swag.IsZero(m.Chunk) { // not required
		return nil
	}

	if m.Chunk != nil {
		if err := m.Chunk.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Chunk")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Chunk")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this file chunk based on the context it is used
func (m *FileChunk) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChunk(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FileChunk) contextValidateChunk(ctx context.Context, formats strfmt.Registry) error {

	if m.Chunk != nil {
		if err := m.Chunk.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Chunk")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Chunk")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FileChunk) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FileChunk) UnmarshalBinary(b []byte) error {
	var res FileChunk
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
