// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// File File information
//
// swagger:model File
type File struct {

	// available
	Available bool `json:"Available,omitempty"`

	// chunks received
	ChunksReceived int64 `json:"ChunksReceived,omitempty"`

	// directory ID
	DirectoryID uint64 `json:"DirectoryID,omitempty"`

	// hash
	Hash string `json:"Hash,omitempty"`

	// ID
	ID uint64 `json:"ID,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// size
	Size int64 `json:"Size,omitempty"`

	// total chunks
	TotalChunks int64 `json:"TotalChunks,omitempty"`
}

// Validate validates this file
func (m *File) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this file based on context it is used
func (m *File) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *File) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *File) UnmarshalBinary(b []byte) error {
	var res File
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
