// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFileUploadRequestAccepted accept the new file upload request and return a UUID for the file
//
// swagger:model NewFileUploadRequestAccepted
type NewFileUploadRequestAccepted struct {

	// upload request Id
	UploadRequestID string `json:"uploadRequestId,omitempty"`
}

// Validate validates this new file upload request accepted
func (m *NewFileUploadRequestAccepted) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this new file upload request accepted based on context it is used
func (m *NewFileUploadRequestAccepted) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewFileUploadRequestAccepted) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewFileUploadRequestAccepted) UnmarshalBinary(b []byte) error {
	var res NewFileUploadRequestAccepted
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
