// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gitlab.computing.dcu.ie/collint9/2021-ca400-collint9-coynemt2/src/client/models"
)

// ListFilesReader is a Reader for the ListFiles structure.
type ListFilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListFilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListFilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 501:
		result := NewListFilesNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListFilesOK creates a ListFilesOK with default headers values
func NewListFilesOK() *ListFilesOK {
	return &ListFilesOK{}
}

/* ListFilesOK describes a response with status code 200, with default header values.

OK
*/
type ListFilesOK struct {
	Payload *models.DirectoryContents
}

func (o *ListFilesOK) Error() string {
	return fmt.Sprintf("[GET /list][%d] listFilesOK  %+v", 200, o.Payload)
}
func (o *ListFilesOK) GetPayload() *models.DirectoryContents {
	return o.Payload
}

func (o *ListFilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DirectoryContents)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListFilesNotImplemented creates a ListFilesNotImplemented with default headers values
func NewListFilesNotImplemented() *ListFilesNotImplemented {
	return &ListFilesNotImplemented{}
}

/* ListFilesNotImplemented describes a response with status code 501, with default header values.

not implemented
*/
type ListFilesNotImplemented struct {
	Payload models.NotImplemented
}

func (o *ListFilesNotImplemented) Error() string {
	return fmt.Sprintf("[GET /list][%d] listFilesNotImplemented  %+v", 501, o.Payload)
}
func (o *ListFilesNotImplemented) GetPayload() models.NotImplemented {
	return o.Payload
}

func (o *ListFilesNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
