// Code generated by go-swagger; DO NOT EDIT.

package transfer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gitlab.computing.dcu.ie/collint9/2021-ca400-collint9-coynemt2/src/client/models"
)

// NewNewUploadParams creates a new NewUploadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNewUploadParams() *NewUploadParams {
	return &NewUploadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNewUploadParamsWithTimeout creates a new NewUploadParams object
// with the ability to set a timeout on a request.
func NewNewUploadParamsWithTimeout(timeout time.Duration) *NewUploadParams {
	return &NewUploadParams{
		timeout: timeout,
	}
}

// NewNewUploadParamsWithContext creates a new NewUploadParams object
// with the ability to set a context for a request.
func NewNewUploadParamsWithContext(ctx context.Context) *NewUploadParams {
	return &NewUploadParams{
		Context: ctx,
	}
}

// NewNewUploadParamsWithHTTPClient creates a new NewUploadParams object
// with the ability to set a custom HTTPClient for a request.
func NewNewUploadParamsWithHTTPClient(client *http.Client) *NewUploadParams {
	return &NewUploadParams{
		HTTPClient: client,
	}
}

/* NewUploadParams contains all the parameters to send to the API endpoint
   for the new upload operation.

   Typically these are written to a http.Request.
*/
type NewUploadParams struct {

	// FileInfo.
	FileInfo *models.FileInfo

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the new upload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NewUploadParams) WithDefaults() *NewUploadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the new upload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NewUploadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the new upload params
func (o *NewUploadParams) WithTimeout(timeout time.Duration) *NewUploadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the new upload params
func (o *NewUploadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the new upload params
func (o *NewUploadParams) WithContext(ctx context.Context) *NewUploadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the new upload params
func (o *NewUploadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the new upload params
func (o *NewUploadParams) WithHTTPClient(client *http.Client) *NewUploadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the new upload params
func (o *NewUploadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFileInfo adds the fileInfo to the new upload params
func (o *NewUploadParams) WithFileInfo(fileInfo *models.FileInfo) *NewUploadParams {
	o.SetFileInfo(fileInfo)
	return o
}

// SetFileInfo adds the fileInfo to the new upload params
func (o *NewUploadParams) SetFileInfo(fileInfo *models.FileInfo) {
	o.FileInfo = fileInfo
}

// WriteToRequest writes these params to a swagger request
func (o *NewUploadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.FileInfo != nil {
		if err := r.SetBodyParam(o.FileInfo); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
